### ISSUE TITLE
Pipe scraped data to machine-learning

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/ist-652#21]
We need to pipe our scraped wikipedia + twitter data, to our [machine-learning](https://github.com/jeff1evesque/machine-learning) application.

**Comment by jeff1evesque** [comment]
Before we send our data payload to our endpoint, we need to restructure the data into an acceptable form. Specifically, each dataset [instance](https://github.com/jeff1evesque/ist-565/blob/master/data/twitter/amazon--2018-09-03T13-12-03.json), will need to be converted into an [acceptable](https://github.com/jeff1evesque/machine-learning/blob/master/interface/static/data/json/programmatic_interface/svm/file_upload/svm-data-new.json) format:

```json
{
	"properties": {
            "session_name": "sample_svm_title",
            "collection": "svm-2",
            "dataset_type": "file_upload",
            "session_type": "data_new",
            "model_type": "svm",
            "stream": "True"
	},
	"dataset": [{
			"dependent-variable": "dep-variable-1",
			"independent-variables": [{
				"indep-variable-1": 23.45,
				"indep-variable-2": 98.01,
				"indep-variable-4": 325,
				"indep-variable-5": 54.64,
				"indep-variable-6": 0.002,
				"indep-variable-7": 23,
				"indep-variable-3": 0.432
			}]
		},
		{
			"dependent-variable": "dep-variable-4",
			"independent-variables": [{
					"indep-variable-1": 22.1,
					"indep-variable-2": 95.96,
					"indep-variable-4": 342,
					"indep-variable-5": 66.67,
					"indep-variable-6": 0.001,
					"indep-variable-7": 32,
					"indep-variable-3": 0.743
				},
				{
					"indep-variable-1": 20.71,
					"indep-variable-2": 99.33,
					"indep-variable-4": 342,
					"indep-variable-5": 75.67,
					"indep-variable-6": 0.001,
					"indep-variable-7": 30,
					"indep-variable-3": 0.648
				}
			]
		},
		{
			"dependent-variable": "dep-variable-5",
			"independent-variables": [{
					"indep-variable-1": 23.27,
					"indep-variable-2": 95.03,
					"indep-variable-4": 295,
					"indep-variable-5": 55.83,
					"indep-variable-6": 0.001,
					"indep-variable-7": 27,
					"indep-variable-3": 0.488
				},
				{
					"indep-variable-1": 23.27,
					"indep-variable-2": 95.03,
					"indep-variable-4": 295,
					"indep-variable-5": 55.83,
					"indep-variable-6": 0.001,
					"indep-variable-7": 27,
					"indep-variable-3": 0.488
				},
				{
					"indep-variable-1": 19.99,
					"indep-variable-2": 97.78,
					"indep-variable-4": 303,
					"indep-variable-5": 58.88,
					"indep-variable-6": 0.001,
					"indep-variable-7": 29,
					"indep-variable-3": 0.638
				}
			]
		},
		{
			"dependent-variable": "dep-variable-3",
			"independent-variables": [{
				"indep-variable-1": 22.67,
				"indep-variable-2": 101.21,
				"indep-variable-4": 427,
				"indep-variable-5": 75.45,
				"indep-variable-6": 0.002,
				"indep-variable-7": 26,
				"indep-variable-3": 0.832
			}]
		}
	]
}
```

**Comment by jeff1evesque** [comment]
Our current `run.py` execution yields the following traceback:

```bash
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 67, in create_con       nection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_requ       est
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 787, in _validate_       conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connec       tion.VerifiedHTTPSConnection object at 0x7f8b1ac215f8>: Failed to establish a new connecti       on: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='True', port=       8585): Max retries exceeded with url: /login (Caused by NewConnectionError('<requests.pack       ages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f8b1ac215f8>: Failed to estab       lish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 61, in <module>
    run(*argv[1:])
  File "run.py", line 57, in run
    port=port
  File "/home/ubuntu/ist-652/utility/wikipedia_scraper.py", line 78, in wikipedia_scraper
    data={'user[login]': username, 'user[password]': password}
  File "/usr/lib/python3/dist-packages/requests/api.py", line 107, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='True', port=8585): Max retr       ies exceeded with url: /login (Caused by NewConnectionError('<requests.packages.urllib3.co       nnection.VerifiedHTTPSConnection object at 0x7f8b1ac215f8>: Failed to establish a new conn       ection: [Errno -2] Name or service not known',))
```

**Comment by jeff1evesque** [comment]
We need to test the following snippet:

```python
                # get access token
                login = requests.post(
                    'https://{}:{}/login'.format(endpoint, port),
                    headers={'Content-Type': 'application/json'},
                    data={'user[login]': username, 'user[password]': password}
                )
                token = login.json['access_token']
                print('token: {}'.format(token))
```

If we cannot get the above working in a suitable amount of time, we can temporarily omit the above, since the current endpoint allows anonymous requests. However, this may not be a long term functionality.

**Comment by jeff1evesque** [comment]
One probable problem is that the corresponding machine-learning application implements a self signed certificate. Additionally, all `http` requests are redirected to `https`. Several possible solutions exists, if implementing the api is still desired:

- acquire + implement signed certificate by an official certificate authority
- acquire certificate file, load it locally, then use the [`verify='/path/to/public_key.pem'`](https://stackoverflow.com/a/30405947) syntax with the corresponding `requests.post`.

**Comment by jeff1evesque** [comment]
This problem is two fold problem:

- valid certificates required (or `requests.post` must ignore validation)
- debugging must begin with nginx, or gunicorn

Therefore, we'll temporarily merge the changes in this issue, and return to it if more time permits. In the meantime, we'll develop an `else` condition. This will generate a csv file, containing the article name, and the predicted article category.
