### ISSUE TITLE
Vectorize stemmed wikipedia summary

### ISSUE THREAD

**Issue by jeff1evesque** [jeff1evesque/ist-652#31]
We should vectorize the stemmed wikipedia article summaries. Specifically, we should pipe the results into some vectorize equivalent logic:

```python
from sklearn.feature_extraction.text import TfidfVectorizer

myTfidf = TfidfVectorizer()
myTfs = myTfidf.fit_transform(myDict.values())
print myTfs.shape
```

**Note:** the above snipped was borrowed from [PythonStartupTutorial-pt2.pdf](https://github.com/jeff1evesque/ist-652/files/2386056/PythonStartupTutorial-pt2.pdf).

**Comment by jeff1evesque** [comment]
We are currently receiving:

```python
root@xxx:/home/ubuntu/ist-652# python3 run.py
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    run(*argv[1:])
  File "run.py", line 74, in run
    datetime.datetime.now().strftime('%Y-%m-%dT%H-%M-%S')
  File "/home/ubuntu/ist-652/utility/tfidf_transform.py", line 25, in tfidf_transform
    json.dump(myTfs, jsonfile, indent=4)
  File "/usr/lib/python3.5/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <1000x1135 sparse matrix of type '<class 'numpy.float64'>'
        with 1380 stored elements in Compressed Sparse Row format> is not JSON serializable
```

**Comment by jeff1evesque** [comment]
We need to verify that the variable `type` for `corpus` is valid per `myTfidf.fit_transform` definition.

**Comment by jeff1evesque** [comment]
Our supplied `corpus` is a type `dict`, while the [`fit_transform`](http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html#sklearn.feature_extraction.text.TfidfVectorizer.fit_transform) requires a sparse matrix.

**Comment by jeff1evesque** [comment]
This issue is not complete.
